-- PRODUCT_DESCRIPTIONS
ALTER TABLE PRODUCT_DESCRIPTIONS CHANGE COLUMN PRODUCT_UNIT PRODUCT_UNIT_ID BIGINT(20) NOT NULL;

ALTER TABLE PRODUCT_DESCRIPTIONS DROP FOREIGN KEY `FK_PRODUCT_DESCRIPTIONS_PRODUCT_UNIT`,
ADD CONSTRAINT `FK_PRODUCT_DESCRIPTIONS_PRODUCT_UNIT_ID` FOREIGN KEY (`PRODUCT_UNIT_ID`) REFERENCES `PRODUCT_UNITS` (`ID`);