
-- RETURN_ITEMS
DROP TABLE `RETURN_ITEMS`;

-- GUIDES
CREATE TABLE `GUIDES` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `RENT_ID` BIGINT(20) NOT NULL,
  `ISSUE_DATE` DATE NOT NULL,
  `GUIDE_TYPE` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_GUIDES_RENT_ID` (`RENT_ID`),
  CONSTRAINT `FK_GUIDES_RENT_ID` FOREIGN KEY (`RENT_ID`) REFERENCES `RENTS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- GUIDE_ITEMS
CREATE TABLE `GUIDE_ITEMS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `GUIDE_ID` BIGINT(20) NOT NULL,
  `RENT_ITEM_ID` BIGINT(20) NOT NULL,
  `QUANTITY` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_GUIDE_ITEMS_GUIDE_ID` (`GUIDE_ID`),
  KEY `FK_GUIDE_ITEMS_RENT_ITEM_ID` (`RENT_ITEM_ID`),
  CONSTRAINT `FK_GUIDE_ITEMS_GUIDE_ID` FOREIGN KEY (`GUIDE_ID`) REFERENCES `GUIDES` (`ID`),
  CONSTRAINT `FK_GUIDE_ITEMS_RENT_ITEM_ID` FOREIGN KEY (`RENT_ITEM_ID`) REFERENCES `RENT_ITEMS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RENT_ITEMS
ALTER TABLE RENT_ITEMS CHANGE COLUMN QUANTITY PLANNED_QUANTITY DECIMAL(19,2) NOT NULL;
ALTER TABLE RENT_ITEMS CHANGE COLUMN TOTAL PLANNED_TOTAL DECIMAL(19,2) NOT NULL;
ALTER TABLE RENT_ITEMS CHANGE COLUMN RETURNABLE STOCKABLE BOOLEAN NOT NULL;

ALTER TABLE RENT_ITEMS MODIFY COLUMN RETURN_STATUS VARCHAR(15) DEFAULT NULL;

ALTER TABLE RENT_ITEMS ADD COLUMN PLANNED_DAYS DECIMAL(19,2) NOT NULL AFTER PLANNED_QUANTITY;
ALTER TABLE RENT_ITEMS ADD COLUMN LOADED_QUANTITY DECIMAL(19,2) DEFAULT NULL AFTER PLANNED_DAYS;
ALTER TABLE RENT_ITEMS ADD COLUMN LOADING_DATE DATE DEFAULT NULL AFTER LOADED_QUANTITY;
ALTER TABLE RENT_ITEMS ADD COLUMN RETURNED_QUANTITY DECIMAL(19,2) DEFAULT NULL AFTER LOADING_DATE;
ALTER TABLE RENT_ITEMS ADD COLUMN RETURN_DATE DATE DEFAULT NULL AFTER RETURNED_QUANTITY;
ALTER TABLE RENT_ITEMS ADD COLUMN CALCULATED_TOTAL DECIMAL(19,2) DEFAULT NULL AFTER PLANNED_TOTAL;
ALTER TABLE RENT_ITEMS ADD COLUMN LOAD_STATUS VARCHAR(15) NOT NULL AFTER STOCKABLE;

ALTER TABLE RENT_ITEMS DROP COLUMN START_DATE;
ALTER TABLE RENT_ITEMS DROP COLUMN END_DATE;
ALTER TABLE RENT_ITEMS DROP COLUMN DESCRIPTION;

-- RENTS
ALTER TABLE RENTS CHANGE COLUMN TOTAL_RENT TOTAL_ESTIMATED DECIMAL(19,2) NOT NULL;
ALTER TABLE RENTS ADD COLUMN TOTAL_CALCULATED DECIMAL(19,2) NOT NULL DEFAULT 0.00 AFTER TOTAL_ESTIMATED;






