-- SALES
 UPDATE SALES SET SALE_STATUS = 'OPENED' WHERE SALE_STATUS = 'PENDING';
 UPDATE SALES SET SALE_STATUS = 'IN_PROGRESS' WHERE SALE_STATUS = 'INCOMPLETE';
 UPDATE SALES SET SALE_STATUS = 'CLOSED' WHERE SALE_STATUS = 'COMPLETE';