-- UNITS
ALTER TABLE GROCERIES ADD COLUMN NUMBER_OF_TABLES INT(20) NOT NULL DEFAULT 10;
ALTER TABLE GROCERIES ADD COLUMN LOGO_PATH VARCHAR(50) DEFAULT NULL;
ALTER TABLE GROCERIES ADD COLUMN SIGNATURE_PATH VARCHAR(50) DEFAULT NULL;

-- SALES
ALTER TABLE SALES ADD COLUMN TABLE_NUMBER INT(20) DEFAULT NULL;