-- PRODUCTS
CREATE TABLE `PRODUCTS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- PRODUCT_UNITS
CREATE TABLE `PRODUCT_UNITS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `PRODUCT_UNIT_TYPE` VARCHAR(10) NOT NULL,
  `UNIT` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- PRODUCT_DESCRIPTIONS
CREATE TABLE `PRODUCT_DESCRIPTIONS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(80) NOT NULL,
  `PRODUCT_ID` BIGINT(20) NOT NULL,
  `PRODUCT_UNIT` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUCT_DESCRIPTIONS_PRODUCT_ID` (`PRODUCT_ID`),
  KEY `FK_PRODUCT_DESCRIPTIONS_PRODUCT_UNIT` (`PRODUCT_UNIT`),
  CONSTRAINT `FK_PRODUCT_DESCRIPTIONS_PRODUCT_UNIT` FOREIGN KEY (`PRODUCT_UNIT`) REFERENCES `PRODUCT_UNITS` (`ID`),
  CONSTRAINT `FK_PRODUCT_DESCRIPTIONS_PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- STOCKS
CREATE TABLE `STOCKS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `PURCHASE_PRICE` DECIMAL(19,2) NOT NULL,
  `QUANTITY` DECIMAL(19,2) NOT NULL,
  `SALE_PRICE` DECIMAL(19,2) NOT NULL,
  `PRODUCT_DESCRIPTION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_STOCKS_PRODUCT_DESCRIPTION_ID` (`PRODUCT_DESCRIPTION_ID`),
  CONSTRAINT `FK_STOCKS_PRODUCT_DESCRIPTION_ID` FOREIGN KEY (`PRODUCT_DESCRIPTION_ID`) REFERENCES `PRODUCT_DESCRIPTIONS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- SALES
CREATE TABLE `SALES` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `TOTAL` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- SALE_ITEMS
CREATE TABLE `SALE_ITEMS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `QUANTITY` DECIMAL(19,2) NOT NULL,
  `SALE_ITEM_VALUE` DECIMAL(19,2) NOT NULL,
  `SALE_ID` BIGINT(20) NOT NULL,
  `STOCK_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SALE_ITEMS_SALE_ID` (`SALE_ID`),
  KEY `FK_FK_SALE_ITEMS_STOCK_ID` (`STOCK_ID`),
  CONSTRAINT `FK_FK_SALE_ITEMS_STOCK_ID` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCKS` (`ID`),
  CONSTRAINT `FK_SALE_ITEMS_SALE_ID` FOREIGN KEY (`SALE_ID`) REFERENCES `SALES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
