-- EXPENSES_TYPE
CREATE TABLE `EXPENSES_TYPE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- EXPENSES
CREATE TABLE `EXPENSES` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `GROCERY_ID` BIGINT NOT NULL,
  `EXPENSE_TYPE_ID` BIGINT NOT NULL,
  `DATE_PERFORMED` DATE NOT NULL,
  `EXPENSE_VALUE` DECIMAL(19,2) NOT NULL,
  `DESCRIPTION` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EXPENSES_GROCERY_ID` (`GROCERY_ID`),
  KEY `FK_EXPENSES_EXPENSE_TYPE_ID` (`EXPENSE_TYPE_ID`),
  CONSTRAINT `FK_EXPENSES_GROCERY_ID` FOREIGN KEY (`GROCERY_ID`) REFERENCES `GROCERIES` (`ID`),
  CONSTRAINT `FK_EXPENSES_EXPENSE_TYPE_ID` FOREIGN KEY (`EXPENSE_TYPE_ID`) REFERENCES `EXPENSES_TYPE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;