-- CUSTOMERS
CREATE TABLE `CUSTOMERS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `UNIT_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL, 
  `ADDRESS` VARCHAR(100) NOT NULL, 
  `CONTACT` VARCHAR(30) NOT NULL,
  `EMAIL` VARCHAR(30) DEFAULT NULL,
  `VEHICLE_NUMBER_PLATE` VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CUSTOMERS_UNIT_ID` (`UNIT_ID`),
  CONSTRAINT `FK_CUSTOMERS_UNIT_ID` FOREIGN KEY (`UNIT_ID`) REFERENCES `GROCERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RENTS
CREATE TABLE `RENTS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `UNIT_ID` BIGINT(20) NOT NULL,
  `CUSTOMER_ID` BIGINT(20) NOT NULL,
  `RENT_DATE` DATE NOT NULL,
  `PAYMENT_STATUS` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RENTS_UNIT_ID` (`UNIT_ID`),
  KEY `FK_RENTS_CUSTOMER_ID` (`CUSTOMER_ID`),
  CONSTRAINT `FK_RENTS_UNIT_ID` FOREIGN KEY (`UNIT_ID`) REFERENCES `GROCERIES` (`ID`),
  CONSTRAINT `FK_RENTS_CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RENT_PAYMENTS
CREATE TABLE `RENT_PAYMENTS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `RENT_ID` BIGINT(20) NOT NULL,
  `PAYMENT_DATE` DATE NOT NULL,
  `PAYMENT_VALUE` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RENT_PAYMENTS_RENT_ID` (`RENT_ID`),
  CONSTRAINT `FK_RENT_PAYMENTS_RENT_ID` FOREIGN KEY (`RENT_ID`) REFERENCES `RENTS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RENT_ITEMS
CREATE TABLE `RENT_ITEMS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `RENT_ID` BIGINT(20) NOT NULL,
  `STOCK_ID` BIGINT(20) DEFAULT NULL,
  `SERVICE_ITEM_ID` BIGINT(20) DEFAULT NULL,
  `QUANTITY` DECIMAL(19,2) NOT NULL,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NOT NULL,
  `DISCOUNT` DECIMAL(19,2) NOT NULL,
  `TOTAL` DECIMAL(19,2) NOT NULL,
  `RETURNABLE` BOOLEAN NOT NULL,
  `RETURN_STATUS` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RENT_ITEMS_RENT_ID` (`RENT_ID`),
  KEY `FK_RENT_ITEMS_STOCK_ID` (`STOCK_ID`),
  KEY `FK_RENT_ITEMS_SERVICE_ITEM_ID` (`SERVICE_ITEM_ID`),
  CONSTRAINT `FK_RENT_ITEMS_RENT_ID` FOREIGN KEY (`RENT_ID`) REFERENCES `RENTS` (`ID`),
  CONSTRAINT `FK_RENT_ITEMS_STOCK_ID` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCKS` (`ID`),
  CONSTRAINT `FK_RENT_ITEMS_SERVICE_ITEM_ID` FOREIGN KEY (`SERVICE_ITEM_ID`) REFERENCES `SERVICE_ITEMS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RETURN_ITEMS
CREATE TABLE `RETURN_ITEMS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `RENT_ITEM_ID` BIGINT(20) NOT NULL,
  `RETURN_DATE` DATE NOT NULL,
  `QUANTITY` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_RETURN_ITEMS_RENT_ITEM_ID` (`RENT_ITEM_ID`),
  CONSTRAINT `FK_RETURN_ITEMS_RENT_ITEM_ID` FOREIGN KEY (`RENT_ITEM_ID`) REFERENCES `RENT_ITEMS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;