-- STOCKS UPDATE
ALTER TABLE `STOCKS` ADD COLUMN `INVENTORY_DATE` DATE;
ALTER TABLE `STOCKS` ADD COLUMN `INVENTORY_QUANTITY` DECIMAL(19,2);
ALTER TABLE `STOCKS` ADD COLUMN `STOCK_UPDATE_DATE` DATE;
ALTER TABLE `STOCKS` ADD COLUMN `STOCK_UPDATE_QUANTITY` DECIMAL(19,2);
ALTER TABLE `STOCKS` ADD COLUMN `PRODUCT_STOCK_STATUS` VARCHAR(50) NOT NULL DEFAULT 'GOOD';

