-- CONTRACTS
CREATE TABLE `CONTRACTS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `UNIT_ID` BIGINT(20) NOT NULL,
  `CUSTOMER_ID` BIGINT(20) NOT NULL,
  `CONTRACT_TYPE` VARCHAR(50) NOT NULL, 
  `DESCRIPTION` VARCHAR(150) NOT NULL, 
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NOT NULL,
  `REFERENCE_PAYMENT_DATE` DATE NOT NULL,
  `MONTHLY_PAYMENT` DECIMAL(19,2) NOT NULL,
  `TOTAL_PAID` DECIMAL(19,2) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CONTRACTS_UNIT_ID` (`UNIT_ID`),
  KEY `FK_CONTRACTS_CUSTOMER_ID` (`CUSTOMER_ID`),
  CONSTRAINT `FK_CONTRACTS_UNIT_ID` FOREIGN KEY (`UNIT_ID`) REFERENCES `GROCERIES` (`ID`),
  CONSTRAINT `FK_CONTRACTS_CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CONTRACT_PAYMENTS
CREATE TABLE `CONTRACT_PAYMENTS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `CONTRACT_ID` BIGINT(20) NOT NULL,
  `PAYMENT_DATE` DATE NOT NULL,
  `REFERENCE_DATE` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CONTRACT_PAYMENTS_CONTRACT_ID` (`CONTRACT_ID`),
  CONSTRAINT `FK_CONTRACT_PAYMENTS_CONTRACT_ID` FOREIGN KEY (`CONTRACT_ID`) REFERENCES `CONTRACTS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CUSTOMERS AND RENT_ITEMS UPDATES
ALTER TABLE `CUSTOMERS` DROP COLUMN `VEHICLE_NUMBER_PLATE`;
ALTER TABLE `RENT_ITEMS` ADD COLUMN  `DESCRIPTION` VARCHAR(150);
