-- RENTS
ALTER TABLE RENTS ADD COLUMN LOAD_STATUS VARCHAR(15) NOT NULL DEFAULT 'PENDING' AFTER PAYMENT_STATUS;
ALTER TABLE RENTS ADD COLUMN RETURN_STATUS VARCHAR(15) NOT NULL DEFAULT 'PENDING' AFTER LOAD_STATUS;






