-- GUIDES
ALTER TABLE GUIDES MODIFY COLUMN RENT_ID BIGINT(20) DEFAULT NULL;
ALTER TABLE GUIDES ADD COLUMN SALE_ID BIGINT(20) DEFAULT NULL AFTER RENT_ID;
ALTER TABLE `GUIDES` ADD CONSTRAINT `FK_GUIDES_SALE_ID` FOREIGN KEY (`SALE_ID`) REFERENCES `SALES` (`ID`);

-- GUIDE_ITEMS
ALTER TABLE GUIDE_ITEMS MODIFY COLUMN RENT_ITEM_ID BIGINT(20) DEFAULT NULL;
ALTER TABLE GUIDE_ITEMS ADD COLUMN SALE_ITEM_ID BIGINT(20) DEFAULT NULL AFTER RENT_ITEM_ID;
ALTER TABLE `GUIDE_ITEMS` ADD CONSTRAINT `FK_GUIDE_ITEMS_SALE_ITEM_ID` FOREIGN KEY (`SALE_ITEM_ID`) REFERENCES `SALE_ITEMS` (`ID`);

-- SALE_ITEMS
ALTER TABLE SALE_ITEMS ADD COLUMN DELIVERED_QUANTITY DECIMAL(19,2) NOT NULL DEFAULT 0.00 AFTER DISCOUNT;
ALTER TABLE SALE_ITEMS ADD COLUMN DELIVERY_STATUS VARCHAR(15) NOT NULL DEFAULT 'NA' AFTER DELIVERED_QUANTITY;

-- STOCKS
ALTER TABLE STOCKS ADD COLUMN UNIT_PER_M2 DECIMAL(19,2) NOT NULL DEFAULT 0.00;

-- SALES
ALTER TABLE SALES ADD COLUMN DELIVERY_STATUS VARCHAR(20) NOT NULL DEFAULT 'NA';